### PR TITLE
Long-term statistics support

### LINKED ISSUE #77: Support long-term statistics
It would be worthwhile to support long-term statistics for entities that support it. There needs to be options to toggle statistics mode on and off, select between the mean, max, min or sum, and select between the period hour, day or month (there is 5min too IIRC).

Apex-charts card already supports long-term statistics. See https://github.com/RomRider/apexcharts-card/blob/master/src/graphEntry.ts#L257 for the if/else clauses with first statistics fetching then normal history fetching. AFAICT the difference is not much and mostly in `_fetchStatistics` vs `_fetchRecent` even though the value of the datapoint then comes from `entry[period]` instead of `entry.state` or an attribute, and the time is gotten from `start`/`end` attributes instead of `entry.last_changed`/`entry.last_updated`. To me it seems that it is not too hard to retrofit the statistics fetching into the format output by `fetchSingleRange()` at https://github.com/dbuezas/lovelace-plotly-graph-card/blob/master/src/Cache.ts#L13

Some example JS code that actually fetches statistics data, filters it and returns a list of `[timestamp, value]` pairs:
```
      const statistics = await hass.callWS({
          type: 'recorder/statistics_during_period',
          start_time: new Date(start).toISOString(),
          end_time: new Date(end).toISOString(),
          statistic_ids: [entity.entity_id],
          period: "hour",
      });
      var result = [];
      statistics[entity.entity_id].forEach( (item) => {
        val = parseFloat(item.mean)
        if (val > 100) {
           result.push([
            ((new Date(mid.start).getTime()) + (new Date(mid.end).getTime()))/2,
            val
          ])
        }
      });
      return result;
```
It is adapted from https://gitlab.com/home-assistant-frnchfrgg/apex-local-extrema/-/blob/main/apex.yaml that I use in production currently (but `lovelace-ploty-graph-card` has features I hope to use, in particular your data mangling feature is not per-point so I could do all this without abusing a data generator).

I would do it myself in a pull request (and maybe will) but since you embed the history entry into the result I would have to check all around what fields you expect to see in users of the cache.

### PR DESCRIPTION
**Pull request by FrnchFrgg**
Fix #77
A followup would be to still ask home assistant for "friendly name" and "unit" metadata because statistics do not contain that information.

### CODE REVIEW

**Comment by dbuezas** [comment]
Looks and works fantastic! 🎉 
I'll add the unit_of_measurement and review it a bit and merge it in the coming days

**Comment by dbuezas** [comment]
I moved things around a bit to reduce file sizes, fixed the types, added units and names and did a small change to the API (mandatory statistics type b/c yamls says so).
Let me know if your yamls still work as intended and we can make a release

**Comment by dbuezas** [comment]
I also changed the default period to 5minute, as that is the only one that seems to be stored by default in HA. Please confirm this is not just a fluke in my HA :) 
If I switch to hour, day, etc, then most of my entities have not data available. 
WDYT?

**Comment by dbuezas** [comment]
I've been thinking about the API, and I think we should stop misusing the entity id.
I originally implemented it as part of the entity field as a quick hack, but it is a really odd api.

I'm thinking of this:
```yaml
- entity: sensor.xyz
  statistic: mean
  period: hour # optional
```
And for attributes like this:
```yaml
- entity: sensor.xyz
  attribute: color
```

I'll keep attributes backwards compatible, but for stats we can do it cleanly from the get go.

**Comment by FrnchFrgg** [comment]
I agree about the API. I used it since it was the existing syntax (and I wanted minimal changes as proof of feasibility), but devising another way to parse and pass options to the data fetcher would be good.

Your syntax proposal is what I expect from similar cards so I'd say it is the most correct. Just a problem (and one other reason I didn't try that route): since every unused option is passed as-is to `plotly` you have to ensure that none of `statistic`, `period` and `attribute` are going to be overloaded.

For the trailing `::` I noticed the problem (and even documented it, advising to either specify a period or quote the whole thing) but with the new and correct syntax it is moot anyway.

Last but not least, the default period should IMHO still be `hour` since shorter periods are a) only kept for a shorter span of time, probably the same as normal history b) using statistics is to access data over longer periods and having too short of a period will generate a lot of datapoints. I do not know why your system does not keep track of long-term statistics correctly. Maybe you have to specify something if you do not use the `default_config:` stanza ?

**Comment by dbuezas** [comment]
> ensure that none of statistic, period and attribute are going to be overloaded.

good point, I just checked and it is ok

> the default period should IMHO still be hour 

Ok, good arguments. Also, to put a nail in my default proposal, hour is used as default in the code you linked here: https://github.com/home-assistant/frontend/blob/dev/src/data/recorder.ts#L113

I'm almost done with the refactor. It will be a braking change because of attributes, but it is better this way imo

**Comment by dbuezas** [comment]
btw, should the attribute be "statistic" or "statistics"? IMO it should be "statistic" (singluar), but maybe the plural is standard somwhere else?

**Comment by dbuezas** [comment]
The code changed quite a bit, hopefully for the better :)

The version is out as v1.4.0 beta, thanks for the contribution!

**Pull request merged**
